Fixed an unhandled exception in aker.py
aker-gateway/Aker pull request #101
Opened 2020-02-29 15:17 UTC by pewo

Small fix to handle a exception in aker.py

2020-03-03 08:58 UTC, EoleDev commented on aker.py
>              session.start_session()
```suggestion
            session.connect(screen_size)
            session.start_session()
        except Exception as e:
            logging.error(
                "Core: Error connection or starting session UUID {0} for user {1} : {2} ".format(
                    session_uuid, self.posix_user, e.message))
            print(e)
            raw_input("Press Enter to continue...")
```

2020-03-03 09:04 UTC, EoleDev requested changes
Hi @pewo,
I think, it's best to put the session connection and start in the same try. It would allow to catch and print the error in the two cases and avoid the code redundancy in the error handling.
I did a quick suggestion on your code and changed two things : 
  - the one mentioned above
  - the logging error message. I changed it to be consistent with the project way of loggging.

@anazmy I would be glad if you could give your opinion about the print and raw_input part. Is there a better way to do it, or is already the best ?

I am not quite proficient with the review system of github, so if I made an error, feel free to correct it!

2020-03-04 20:47 UTC, pewo commented on aker.py
>              session.start_session()
Looks much better!

2020-03-05 08:21 UTC, EoleDev approved these changes
All seems good for me.
We will need your review @anazmy !
And if you may merge it after, we would be glad!

2020-03-05 20:41 UTC, anazmy commented
The PR has a problem if the failed/offline server is not the first one tried. i.e. try connecting to an online server first then to an offline server. there is still an error.

Need to look into that further.

2020-03-06 13:34 UTC, anazmy commented
Fixed the stdin issue by modifying `SSHClient.py`. The PR looks good now.

Thx a lot @pewo and @EoleDev

2020-03-06 13:35 UTC, anazmy commented
Fixes #98

2020-03-06 13:35 UTC, merged